# aarch64 via UEFI for all UEFI-enabled boards
declare -g BOARD_NAME="UEFI arm64 (QEMU)"
declare -g BOARDFAMILY="uefi-arm64"
declare -g BOARD_MAINTAINER="jjm2473"
declare -g KERNEL_TARGET="current,edge,legacy,cloud"
declare -g KERNEL_TEST_TARGET="current"
declare -g SERIALCON="ttyAMA0"
declare -g BOOT_LOGO=desktop


function post_family_tweaks__qemu-uefi-arm64-clean-firmware() {
	display_alert "$BOARD" "Remove useless firmwares for arm64 virt platform" "info"
	echo "Before:"
	ls "${SDCARD}"/lib/firmware/
	echo "qcom/:"
	ls "${SDCARD}"/lib/firmware/qcom/

	rm -rf "${SDCARD}"/lib/firmware/{ap62*,arm,imx,meson,rkwifi,rockchip,vpu}
	find "${SDCARD}"/lib/firmware/qcom -maxdepth 1 -mindepth 1 \
		-not -name 'aic*' \
		-not -name 'sdx*' \
		-not -name 'prog_firehose_sdx*' \
		-exec rm -rf '{}' ';'

	echo
	echo "After:"
	ls "${SDCARD}"/lib/firmware/
	echo "qcom/:"
	ls "${SDCARD}"/lib/firmware/qcom/
	return 0
}
